// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClXGz449mrBLqMfLCDrCPFbjpw3qQ28-g',
    appId: '1:619009500383:web:242e2173e7776f6dcc756a',
    messagingSenderId: '619009500383',
    projectId: 'todo-45656565',
    authDomain: 'todo-45656565.firebaseapp.com',
    storageBucket: 'todo-45656565.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcKfaPG0hV-foThB9bnCRzLi6QDiUHJTw',
    appId: '1:619009500383:android:51cb401f962ad5e5cc756a',
    messagingSenderId: '619009500383',
    projectId: 'todo-45656565',
    storageBucket: 'todo-45656565.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOfa72cBAFWDKtvj4cs6KQ-5EL6qX5E2c',
    appId: '1:619009500383:ios:c81b5f92e2f60796cc756a',
    messagingSenderId: '619009500383',
    projectId: 'todo-45656565',
    storageBucket: 'todo-45656565.firebasestorage.app',
    iosBundleId: 'com.example.simpleTodo',
  );
}
